// <auto-generated />
namespace DreamLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Roles));
        
        string IMigrationMetadata.Id
        {
            get { return "201711092036076_Roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
